---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: echo
spec:
  params:
    - name: pipelineTask-retries
    - name: pipelineTask-retry-count
  steps:
    - name: collect-data
      image: quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
      script: |
        #!/usr/bin/env sh
        if [ "$(params.pipelineTask-retry-count)" == "$(params.pipelineTask-retries)" ]; then
          echo "This is the last retry."
          exit 0;
        fi
        echo "The PipelineTask has retried $(params.pipelineTask-retry-count) times."
        echo "pipelineTask-retries = $(params.pipelineTask-retries)" 
        exit 1
